### ISSUE TITLE
2 for 1: `WSServerHandshakeError: 400` and `ClientConnectorError: Cannot connect...no address`

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#11]
Unsee alpha has been relabeled to old unsee, unsee beta has been released and is now the new unsee. Currently, receiving errors on both. 

1. Unsee Alpha

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/main.py", line 23, in download_old
    await client.download_album(album_id)
  File "/usr/local/lib/python3.8/site-packages/unsee_dl/unsee_dl.py", line 46, in download_album
    async with self.session.ws_connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 733, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 400, message='Invalid response status', url=URL('wss://ws.unsee.cc/settings/?album=9ee5e20e&name=Leonel')
```

I have not quite figured out websockets yet, so I am lost as for what this error could be.

2. Unsee Beta

```
Traceback (most recent call last):                                                                                                                           
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection                                                 
    hosts = await asyncio.shield(self._resolve_host(                                                                                                         
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host                                                             
    addrs = await \                                                                                                                                          
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve                                                                     
    infos = await self._loop.getaddrinfo(                                                                                                                    
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo                                                                           
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] no address associated with name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/unsee-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/main.py", line 14, in main
    asyncio.get_event_loop().run_until_complete(run_downloader())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/main.py", line 98, in run_downloader
    await download_beta(album_ids_beta_version, args.out_dir, args.group_album)
  File "/usr/local/lib/python3.8/site-packages/main.py", line 33, in download_beta
    await client.anonymous_login()
  File "/usr/local/lib/python3.8/site-packages/unsee_dl/unsee_beta.py", line 58, in anonymous_login
    async with self.session.post(_GRAPHQL_URL, json=gql_body) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api3.unsee.cc:443 ssl:default [no address associated with name]
```
 
The above might be something as simple as the server listening on a different subdomain, for example listening on api.unsee.cc instead of api3.unsee.cc. 

---

Both errors began to occur at the same time which was very early in the morning at around 7 am Berlin time. The change was also instantaneous, one minute it was working and the next minute it was not.

**Comment by anoduck** [comment]
**RESOLVED!!!**

@andsala I finally took my head out of my rear end and used the firefox console... Sometimes, I am thick as mud.

- [ ] Change websocket address for unsee alpha to:  

```
_UNSEE_WEBSOCKET_URL = "wss://old-ws.unsee.cc/{}/"
```

- [ ] Change api address for unsee beta to:

```
_GRAPHQL_URL = "https://api.unsee.cc/graphql"
```

Done and fixed!

**Comment by andsala** [comment]
It sounds good to me, could you submit a PR. I'll publish an update ASAP.

**Comment by anoduck** [comment]
I will within the next day or two, it works well.
