### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#18]
I am not getting anything to download both in old and new. When running the script for the pypi installed package, I received the following error:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/main.py", line 23, in download_old
    await client.download_album(album_id)
  File "/usr/local/lib/python3.9/site-packages/unsee_dl/unsee_old.py", line 116, in download_album
    settings = json.loads(data.data, encoding="utf-8")
  File "/usr/local/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
But, when I run it directly from the reposity, I don't recieve the same error. Just a simple `Found album   with 0 images`.

**Comment by anoduck** [comment]
Simply removed phrase, "encoding="utf-8"" from `json.loads()` and it works.

**Comment by anoduck** [comment]
Recieving:
```
Downloading album ...
Found album  with 0 images....
```

Both unsee old and new, regardless of actual album content. 

Setup test unsee session for kicks: https://old.unsee.cc/album#e1d6e44c
