### ISSUE TITLE
Broken and fails in unsee Beta.

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#9]
Something must have changed with unsee's API, I am getting the same error that the server has disconnected. Here is my output:

```python
Traceback (most recent call last):
  File "/usr/local/bin/unsee-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/main.py", line 13, in main
    asyncio.get_event_loop().run_until_complete(run_downloader())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/main.py", line 78, in run_downloader
    await client.anonymous_login()
  File "/usr/local/lib/python3.8/site-packages/unsee_dl/unsee_beta.py", line 60, in anonymous_login
    async with self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```
Command flat out fails on attempt to download unsee-beta galleries. Does not even make the initially connection to pull down quantity in gallery.

**Comment by anoduck** [comment]
It seems that unsee-dl is having issues creating a session or is receiving an erroneous response for the server.

**Comment by anoduck** [comment]
After doing a bit of troubleshooting, trying different python versions in virtual environments and testing api.unsee.cc/graphql, I am confident in resolving that the API has changed for unsee-beta, and unsee-dl is recieving a response that it was not expecting or cannot understand.

**Comment by anoduck** [comment]
I have got to learn python to help you maintain this project.
